[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[FILTER]
    # Este filtro tenta parsear o campo 'log' como JSON
    # Útil se você estiver usando o driver de log 'fluentd' do Docker
    Name         record_modifier
    Match        *
    Record       service_name magabip

[OUTPUT]
    Name  stdout
    Match *

# Exemplo de saída para o Loki (descomente se for usar)
#[OUTPUT]
#    Name   loki
#    Match  *
#    Host   loki
#    Port   3100
#    Labels job=magabip
