"""add email to user

Revision ID: 2c1cc7a4dcd5
Revises: 
Create Date: 2026-02-18 03:50:05.417415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c1cc7a4dcd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), unique=True, nullable=True))
    # Se precisar remover a tabela coletores_mestre e dependências:
    op.execute("DROP TABLE IF EXISTS coletores_mestre CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('turno', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('alerta_ti',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('colaborador', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('equipamento', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alerta_ti_pkey'))
    )
    op.create_table('colaboradores',
    sa.Column('id_colab', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('turno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('force_pw_change', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_colab', name=op.f('colaboradores_pkey'))
    )
    op.create_table('device_health',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('battery_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('battery_voltage', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('rssi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uptime_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reset_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('device_health_pkey'))
    )
    op.create_index(op.f('idx_health_device_date'), 'device_health', ['device_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('historico',
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('coletor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_acao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_colab', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('setor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('turno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_hora', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_registro', name=op.f('historico_pkey'))
    )
    op.create_table('behavior_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('behavior_logs_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('behavior_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('behavior_logs_pkey'))
    )
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('zendesk_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), server_default=sa.text("'operacao'::character varying"), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=100), server_default=sa.text("'bom'::character varying"), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_inventory_check', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], name=op.f('devices_current_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('devices_pkey')),
    sa.UniqueConstraint('name', name=op.f('devices_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('turno', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('chamados_suporte',
    sa.Column('id_chamado', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coletor_nome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticket_zendesk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_abertura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_fechamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aberto_por', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fechado_por', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solucao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gchat_thread_ti', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gchat_thread_lider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coletor_nome'], ['coletores_mestre.coletor'], name=op.f('chamados_suporte_coletor_nome_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_chamado', name=op.f('chamados_suporte_pkey'))
    )
    op.create_table('lideres',
    sa.Column('id_lider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('turno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_lider', name=op.f('lideres_pkey'))
    )
    op.create_table('coletores_status',
    sa.Column('coletor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ns_coletor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_hora', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usuario_atual', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coletor'], ['coletores_mestre.coletor'], name=op.f('coletores_status_coletor_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coletor', name=op.f('coletores_status_pkey'))
    )
    op.create_table('analistas_ti',
    sa.Column('id_analista', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('login_rede', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_analista', name=op.f('analistas_ti_pkey'))
    )
    op.create_table('faqs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('relevance_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('faqs_pkey'))
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('zendesk_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reported_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zendesk_added_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolved_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('colaborador_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('colaborador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ti_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ti_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('support_tickets_device_id_fkey')),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('support_tickets_reported_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('support_tickets_resolved_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['zendesk_added_by_user_id'], ['users.id'], name=op.f('support_tickets_zendesk_added_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('support_tickets_pkey'))
    )
    op.create_table('technical_docs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('technical_docs_pkey'))
    )
    op.create_table('checkout_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checkout_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('checkin_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('colaborador_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('colaborador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ti_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ti_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('checkout_logs_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checkout_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('checkout_logs_pkey'))
    )
    op.create_table('coletores_mestre',
    sa.Column('coletor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ns_coletor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('coletor', name=op.f('coletores_mestre_pkey'))
    )
    # Remover a tabela coletores_mestre e dependências, se necessário
    # op.execute("DROP TABLE coletores_mestre CASCADE")
    # ### end Alembic commands ###
